version: '3'
services:
  reverse-proxy:
    image: nginx:1.23
    volumes:
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    networks:
      - frontend
  react-landing:
    image: nginx:1.23
    volumes:
      - ./services/crypto-wallet-landing:/app
      - ./services/crypto-wallet-landing/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
  react-wallet:
    build:
      context: services/crypto-wallet-frontend
      dockerfile: docker/dev/Dockerfile
    container_name: react-wallet
    stdin_open: true
    volumes:
      - ./services/crypto-wallet-frontend:/app
      - /app/node_modules/
    networks:
      - frontend
networks:
  frontend:
    driver: bridge