version: '3'
services:
  load-balance:
    build:
      context: docker/shared/nginx
    environment:
      DOMAIN_NAME: '${DOMAIN_NAME}'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - frontend
    depends_on:
      - react-landing
      - react-wallet
  react-landing:
    build:
      context: services/crypto-wallet-landing
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./services/crypto-wallet-landing:/app
    networks:
      - frontend
  react-wallet:
    build:
      context: services/crypto-wallet-frontend
      dockerfile: docker/local/Dockerfile
    volumes:
      - ./services/crypto-wallet-frontend:/app
      - /app/node_modules/
    networks:
      - frontend
networks:
  frontend:
    driver: bridge