apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react-wallet
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: react-wallet
          name: react-wallet
          resources: {}
          stdin: true
          volumeMounts:
            - mountPath: /app
              name: react-wallet-claim0
            - mountPath: /app/node_modules/
              name: react-wallet-claim1
      restartPolicy: Always
      volumes:
        - name: react-wallet-claim0
          persistentVolumeClaim:
            claimName: react-wallet-claim0
        - name: react-wallet-claim1
          persistentVolumeClaim:
            claimName: react-wallet-claim1
status: {}
