apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: react-landing
  name: react-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react-landing
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/frontend: "true"
        io.kompose.service: react-landing
    spec:
      containers:
        - image: nginx:1.23
          name: react-landing
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: react-landing-claim0
            - mountPath: /etc/nginx/nginx.conf
              name: react-landing-claim1
      restartPolicy: Always
      volumes:
        - name: react-landing-claim0
          persistentVolumeClaim:
            claimName: react-landing-claim0
        - name: react-landing-claim1
          persistentVolumeClaim:
            claimName: react-landing-claim1
status: {}
